ChiaSeCode_TH/Controllers/DangKyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChiaSeCode_TH.Models;

namespace ChiaSeCode_TH.Controllers
{
    public class DangKyController : Controller
    {
        FreeCodeEntities db = new FreeCodeEntities();
        // GET: DangKy
        public ActionResult DangKy()
        {
            ViewBag.MaVaiTro = new SelectList(db.VaiTroes, "MaVaiTro", "TenVaiTro");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DangKy([Bind(Include = "MaNguoiDung,Email,MatKhau,NhapLaiMatKhau,MaVaiTro,Ten,TenHienThi,SoDienThoai,Token")] NguoiDung nguoiDung)
        {
            if (ModelState.IsValid)
            {
                nguoiDung.Token = Guid.NewGuid().ToString();
                db.NguoiDungs.Add(nguoiDung);
                db.SaveChanges();
                return RedirectToAction("ThongBao");
            }

            ViewBag.MaVaiTro = new SelectList(db.VaiTroes, "MaVaiTro", "TenVaiTro", nguoiDung.MaVaiTro);
            return View(nguoiDung);
        }
        public ActionResult ThongBao()
        {
            return View();
        }
        public JsonResult ktraTK(string Email)
        {
            bool Exists = db.NguoiDungs.FirstOrDefault(t => t.Email == Email) != null;
            return Json(!Exists, JsonRequestBehavior.AllowGet);
        }
    }
}

ChiaSeCode_TH/Controllers/HienThiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChiaSeCode_TH.Controllers
{
    public class HienThiController : Controller
    {
        // GET: HienThi
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult ThanhCongCu()
        {
            return PartialView();
        }
        public PartialViewResult Menu()
        {
            return PartialView();
        }
        public PartialViewResult TrangChu2()
        {
            return PartialView();
        }
        public PartialViewResult ChanTK()
        {
            return PartialView();
        }
        public PartialViewResult MenuAll()
        {
            return PartialView();
        }
        public PartialViewResult MenuTinTuc()
        {
            return PartialView();
        }
        public PartialViewResult MenuNo()
        {
            return PartialView();
        }
        public PartialViewResult ChanTrang()
        {
            return PartialView();
        }
    }
}

ChiaSeCode_TH/Views/DangKy/DangKy.cshtml
@using ChiaSeCode_TH.Models;
@model NguoiDung
@{
    NguoiDung ses = (NguoiDung)Session["NguoiDung"];
    NguoiDung sesad = (NguoiDung)Session["Admin"];
}
@{
    ViewBag.Title = "DangKy";
    Layout = "~/Views/Layout/Layout.cshtml";
}


@Html.Action("DangNhap", "DangNhap")
<!--Menu-->
@Html.Action("MenuNo", "HienThi")
<!--//Menu-->
<!--Thanh công cụ-->
@Html.Action("ThanhCongCu", "HienThi")
<!--//Thanh công cụ-->
<!--Giao diện trang chủ-->
<div class="content_middle">
    <div class="container">
        <div class="content_middle_box">
            @if (ses != null)
            {
                Response.Redirect("/HienThi/Index");
            }
            else if (sesad != null)
            {
                <div class="living_middle">
                    <div class="container" style="margin-top: -8%">
                        <div class="col-md-4 wow fadeInLeft" data-wow-delay="0.4s">

                            <ul class="feature">
                                <li>
                                    <div class="alert alert-danger">
                                        <center><b style="color: green">Lợi ích của thành viên FreeCode</b></center>
                                        <ol>
                                            <li>Tải và chia sẽ code của mình.</li>
                                            <li>Tham gia Event.</li>
                                            <li>Khi chia sẻ, nếu code hay admin FreeCode sẽ mua.</li>
                                            <li>Làm quen với nhiều lập trình viên.</li>
                                            <li>Tham gia học hỏi, xem code của thành viên khác.</li>
                                        </ol>
                                    </div>
                                </li>
                                <div class="clearfix"></div>
                            </ul>
                            <ul class="feature">
                                <li>
                                    <div class="alert alert-danger">
                                        <center><b style="color: green">Thống kê thành viên</b></center>
                                        <ul>
                                            <li>Số thành viên:<span>0</span></li>
                                            <li>Số thành viên Online:<span>0</span></li>
                                            <li>Số lượt truy cập: <span>0</span></li>
                                        </ul>
                                    </div>
                                </li>
                                <div class="clearfix"></div>
                            </ul>
                            <ul class="feature last_grid">
                                <li>
                                    <div class="alert alert-success">
                                        <center><a class="btn btn-danger" data-toggle="modal" data-target="#myModal"><b>ĐĂNG NHẬP</b></a></center>
                                    </div>
                                </li>
                                <div class="clearfix"></div>
                            </ul>
                        </div>
                        @*Phải*@
                        <div class="col-md-8 wow fadeInRight" data-wow-delay="0.4s">
                            <div class="educate_grid">
                                <h1>Bạn là admin không thể đăng ký! Có thể thêm trong quản lý</h1>
                            </div>
                        </div>
                    </div>
                </div>
            }
            else
            {
                <div class="living_middle">
                    <div class="container" style="margin-top: -8%">
                        <div class="col-md-4 wow fadeInLeft" data-wow-delay="0.4s">

                            <ul class="feature">
                                <li>
                                    <div class="alert alert-danger">
                                        <center><b style="color: green">Lợi ích của thành viên FreeCode</b></center>
                                        <ol>
                                            <li>Tải và chia sẽ code của mình.</li>
                                            <li>Tham gia Event.</li>
                                            <li>Khi chia sẻ, nếu code hay admin FreeCode sẽ mua.</li>
                                            <li>Làm quen với nhiều lập trình viên.</li>
                                            <li>Tham gia học hỏi, xem code của thành viên khác.</li>
                                        </ol>
                                    </div>
                                </li>
                                <div class="clearfix"></div>
                            </ul>
                            <ul class="feature">
                                <li>
                                    <div class="alert alert-danger">
                                        <center><b style="color: green">Thống kê thành viên</b></center>
                                        <ul>
                                            <li>Số thành viên:<span>0</span></li>
                                            <li>Số thành viên Online:<span>0</span></li>
                                            <li>Số lượt truy cập: <span>0</span></li>
                                        </ul>
                                    </div>
                                </li>
                                <div class="clearfix"></div>
                            </ul>
                            <ul class="feature last_grid">
                                <li>
                                    <div class="alert alert-success">
                                        <center><a class="btn btn-danger" data-toggle="modal" data-target="#myModal"><b>ĐĂNG NHẬP</b></a></center>
                                    </div>
                                </li>
                                <div class="clearfix"></div>
                            </ul>
                        </div>
                        @*Phải*@
                        <div class="col-md-8 wow fadeInRight" data-wow-delay="0.4s">
                            <div class="educate_grid">
                                @using (Html.BeginForm())
                                {
                                    @Html.AntiForgeryToken()

                                    <div class="form-horizontal">
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                        <div class="form-group container">
                                            <b class="control-label col-md-2">Họ tên<span style="color: red">*</span></b>
                                            <div class="col-md-7">
                                                <input type="text" placeholder="VD: Huỳnh Minh Tấn" required class="form-control" name="Ten" />
                                                @Html.ValidationMessageFor(model => model.Ten, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="form-group container">
                                            <b class="control-label col-md-2">Email<span style="color: red">*</span></b>
                                            <div class="col-md-7">
                                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group container">
                                            <b class="control-label col-md-2">Mật khẩu<span style="color: red">*</span></b>
                                            <div class="col-md-7">
                                                @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
                                                @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group container">
                                            <b class="control-label col-md-2">Nhập lại mật khẩu<span style="color: red">*</span></b>
                                            <div class="col-md-7">
                                                @Html.EditorFor(model => model.NhapLaiMatKhau, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
                                                @Html.ValidationMessageFor(model => model.NhapLaiMatKhau, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group container">
                                            <b class="control-label col-md-2">Tên hiển thị<span style="color: red">*</span></b>
                                            <div class="col-md-7">
                                                <input type="text" placeholder="VD: Tanhuynh1999" required class="form-control" name="TenHienThi" />
                                                @Html.ValidationMessageFor(model => model.TenHienThi, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group container">
                                            <b class="control-label col-md-2">Số điện thoại <span style="color: red">*</span></b>
                                            <div class="col-md-7">
                                                <input type="text" placeholder="VD: 0924404019" required class="form-control" name="SoDienThoai" />
                                                @Html.ValidationMessageFor(model => model.SoDienThoai, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-md-7" style="margin-left: 27%">
                                            <input type="checkbox" required /><a href="#" style="color: #fe423f;">Tôi đồng ý với điều khoản sử dụng</a>
                                        </div>
                                        <br /><br />
                                        <div class="form-group">
                                            <div class="col-md-offset-2 col-md-10" style="margin-left: 50%">
                                                <input type="submit" value="Đăng ký" class="btn btn-danger" style="width: 20%" />
                                            </div>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            }
            @Html.Action("TrangChu2", "HienThi")
            <div class="top_grid wow fadeInRight" data-wow-delay="0.4s">
                @Html.Action("TatCaCodeWebsite", "LocCode")
                <div class="clearfix"> </div>
                @Html.Action("TatCaCodeGame", "LocCode")
                <div class="clearfix"> </div>
                @Html.Action("TatCaCodeUngDung", "LocCode")
                <div class="clearfix"> </div>
            </div>
        </div>
        @Html.Action("ChanTK", "HienThi")
    </div>
</div>
@Html.Action("ChanTrang", "HienThi")

ChiaSeCode_TH/Views/DangKy/ThongBao.cshtml
@using ChiaSeCode_TH.Models;
@model NguoiDung
@{
    NguoiDung ses = (NguoiDung)Session["NguoiDung"];
}
@{
    ViewBag.Title = "ThongBao";
    Layout = "~/Views/Layout/Layout.cshtml";
}
@Html.Action("DangNhap", "DangNhap")
<!--Menu-->
@Html.Action("MenuNo", "HienThi")
<!--//Menu-->
<!--Thanh công cụ-->
@Html.Action("ThanhCongCu", "HienThi")
<!--//Thanh công cụ-->
<!--Giao diện trang chủ-->
<div class="content_middle">
    <div class="container">
        <div class="content_middle_box">
            @if (ses != null)
            {
                Response.Redirect("/HienThi/Index");
            }
            else
            {
                <div class="living_middle">
                    <div class="container" style="margin-top: -8%">
                        <div class="col-md-4 wow fadeInLeft" data-wow-delay="0.4s">

                            <ul class="feature">
                                <li>
                                    <div class="alert alert-danger">
                                        <center><b style="color: green">Lợi ích của thành viên FreeCode</b></center>
                                        <ol>
                                            <li>Tải và chia sẽ code của mình.</li>
                                            <li>Tham gia Event.</li>
                                            <li>Khi chia sẻ, nếu code hay admin FreeCode sẽ mua.</li>
                                            <li>Làm quen với nhiều lập trình viên.</li>
                                            <li>Tham gia học hỏi, xem code của thành viên khác.</li>
                                        </ol>
                                    </div>
                                </li>
                                <div class="clearfix"></div>
                            </ul>
                            <ul class="feature">
                                <li>
                                    <div class="alert alert-danger">
                                        <center><b style="color: green">Thống kê thành viên</b></center>
                                        <ul>
                                            <li>Số thành viên:<span>0</span></li>
                                            <li>Số thành viên Online:<span>0</span></li>
                                            <li>Số lượt truy cập: <span>0</span></li>
                                        </ul>
                                    </div>
                                </li>
                                <div class="clearfix"></div>
                            </ul>
                            <ul class="feature last_grid">
                                <li>
                                    <div class="alert alert-success">
                                        <center><a class="btn btn-danger" data-toggle="modal" data-target="#myModal"><b>ĐĂNG NHẬP</b></a></center>
                                    </div>
                                </li>
                                <div class="clearfix"></div>
                            </ul>
                        </div>
                        @*Phải*@
                        <div class="col-md-8 wow fadeInRight" data-wow-delay="0.4s">
                            <div class="educate_grid">
                                <h1>Bạn đã đăng ký thành công! Vui lòng đăng nhập</h1>
                                <a class="btn btn-danger" data-toggle="modal" data-target="#myModal"><b>ĐĂNG NHẬP</b></a>
                            </div>
                        </div>
                    </div>
                </div>
            }
            @Html.Action("DangNhap", "DangNhap")
            @Html.Action("TrangChu2", "HienThi")
            <div class="top_grid wow fadeInRight" data-wow-delay="0.4s">
                @Html.Action("TatCaCodeWebsite", "LocCode")
                <div class="clearfix"> </div>
                @Html.Action("TatCaCodeGame", "LocCode")
                <div class="clearfix"> </div>
                @Html.Action("TatCaCodeUngDung", "LocCode")
                <div class="clearfix"> </div>
            </div>
        </div>
        @Html.Action("ChanTK", "HienThi")
    </div>
</div>
@Html.Action("ChanTrang", "HienThi")