ChiaSeCode_TH/Models/TinTuc.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChiaSeCode_TH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int MaTinTuc { get; set; }
        public string TenTinTuc { get; set; }
        public Nullable<System.DateTime> NgayDangTinTuc { get; set; }
        public string NoiDungTinTuc { get; set; }
        public Nullable<int> MaNguoiDung { get; set; }
        public Nullable<int> MaTheLoaiTinTuc { get; set; }
        public string AnhTinTuc { get; set; }
        public Nullable<int> LuotXemTinTuc { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual TheLoaiTinTuc TheLoaiTinTuc { get; set; }
    }
}

ChiaSeCode_TH/Areas/Admin/Controllers/TinTucsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ChiaSeCode_TH.Models;
using PagedList;

namespace ChiaSeCode_TH.Areas.Admin.Controllers
{
    public class TinTucsController : Controller
    {
        private FreeCodeEntities db = new FreeCodeEntities();

        // GET: Admin/TinTucs
        public ActionResult Index(int? page)
        {
            int pagesize = 12;
            int pagenumber = (page ?? 1);
            var tinTucs = db.TinTucs.Include(t => t.NguoiDung).Include(t => t.TheLoaiTinTuc);
            return View(tinTucs.OrderBy(n => n.TenTinTuc).ToPagedList(pagenumber, pagesize));
        }

        // GET: Admin/TinTucs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            return View(tinTuc);
        }

        // GET: Admin/TinTucs/Create
        public ActionResult Create()
        {
            ViewBag.MaNguoiDung = new SelectList(db.NguoiDungs, "MaNguoiDung", "Email");
            ViewBag.MaTheLoaiTinTuc = new SelectList(db.TheLoaiTinTucs, "MaTheLoaiTinTuc", "TenTheLoaiTinTuc");
            return View();
        }

        // POST: Admin/TinTucs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaTinTuc,TenTinTuc,NgayDangTinTuc,NoiDungTinTuc,MaNguoiDung,MaTheLoaiTinTuc,AnhTinTuc,LuotXemTinTuc")] TinTuc tinTuc, HttpPostedFileBase fileUpload)
        {
            //Lưu tên file ảnh
            var fileimg = Path.GetFileName(fileUpload.FileName);
            //Lưu file
            var pa = Path.Combine(Server.MapPath("~/HinhAnh"), fileimg);
            if (fileUpload == null)
            {
                ViewBag.ThongBao = "Chọn hình ảnh";
                return View();
            }
            else if (System.IO.File.Exists(pa))
            {
                ViewBag.ThongBao = "Hình ảnh đã tồn tại!";
            }
            else
            {
                fileUpload.SaveAs(pa);
            }
            tinTuc.AnhTinTuc = fileUpload.FileName;
            tinTuc.NgayDangTinTuc = DateTime.Now;
            db.TinTucs.Add(tinTuc);
            ViewBag.MaNguoiDung = new SelectList(db.NguoiDungs, "MaNguoiDung", "Email", tinTuc.MaNguoiDung);
            ViewBag.MaTheLoaiTinTuc = new SelectList(db.TheLoaiTinTucs, "MaTheLoaiTinTuc", "TenTheLoaiTinTuc", tinTuc.MaTheLoaiTinTuc);
            db.SaveChanges();
            return View(tinTuc);
        }

        // GET: Admin/TinTucs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaNguoiDung = new SelectList(db.NguoiDungs, "MaNguoiDung", "Email", tinTuc.MaNguoiDung);
            ViewBag.MaTheLoaiTinTuc = new SelectList(db.TheLoaiTinTucs, "MaTheLoaiTinTuc", "TenTheLoaiTinTuc", tinTuc.MaTheLoaiTinTuc);
            return View(tinTuc);
        }

        // POST: Admin/TinTucs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaTinTuc,TenTinTuc,NgayDangTinTuc,NoiDungTinTuc,MaNguoiDung,MaTheLoaiTinTuc,AnhTinTuc,LuotXemTinTuc")] TinTuc tinTuc)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tinTuc).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaNguoiDung = new SelectList(db.NguoiDungs, "MaNguoiDung", "Email", tinTuc.MaNguoiDung);
            ViewBag.MaTheLoaiTinTuc = new SelectList(db.TheLoaiTinTucs, "MaTheLoaiTinTuc", "TenTheLoaiTinTuc", tinTuc.MaTheLoaiTinTuc);
            return View(tinTuc);
        }

        // GET: Admin/TinTucs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            return View(tinTuc);
        }

        // POST: Admin/TinTucs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TinTuc tinTuc = db.TinTucs.Find(id);
            db.TinTucs.Remove(tinTuc);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ChiaSeCode_TH/Controllers/TinTucController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChiaSeCode_TH.Models;

namespace ChiaSeCode_TH.Controllers
{
    public class TinTucController : Controller
    {
        FreeCodeEntities db = new FreeCodeEntities();
        // GET: TinTuc
        public ActionResult TrangChuTinTin()
        {
            return View();
        }
        public PartialViewResult TinTucXemNhieu()
        {
            return PartialView(db.TinTucs.OrderByDescending(n=>n.LuotXemTinTuc).Take(1).ToList());
        }
        public PartialViewResult TinTucMoiNhat()
        {
            return PartialView(db.TinTucs.OrderByDescending(n => n.NgayDangTinTuc).Take(2).ToList());
        }
        public PartialViewResult TinTucXemNhieu2()
        {
            return PartialView(db.TinTucs.OrderByDescending(n => n.LuotXemTinTuc).Take(8).ToList());
        }
        public PartialViewResult TinTuc()
        {
            return PartialView(db.TinTucs.Where(n=>n.MaTheLoaiTinTuc == 3).OrderByDescending(n => n.NgayDangTinTuc).Take(4).ToList());
        }
        public PartialViewResult ThuThuat()
        {
            return PartialView(db.TinTucs.Where(n => n.MaTheLoaiTinTuc == 2).OrderByDescending(n => n.NgayDangTinTuc).Take(4).ToList());
        }
        public PartialViewResult KienThuc()
        {
            return PartialView(db.TinTucs.Where(n => n.MaTheLoaiTinTuc == 1).OrderByDescending(n => n.NgayDangTinTuc).Take(4).ToList());
        }
        public ViewResult XemChiTietTinTuc(int matintuc = 0)
        {
            TinTuc tt = db.TinTucs.SingleOrDefault(n => n.MaTinTuc == matintuc);
            if(tt == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(tt);
        }
        public PartialViewResult DanhSachTheLoai()
        {
            return PartialView(db.TheLoaiTinTucs.ToList());
        }
        public ActionResult LocTheoTheLoaiTinTuc(int matheloaitintuc = 0)
        {
            TheLoaiTinTuc tt = db.TheLoaiTinTucs.SingleOrDefault(n => n.MaTheLoaiTinTuc == matheloaitintuc);
            if (tt == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            Session["TheLoaiTinTuc"] = tt;
            List<TinTuc> tintuc = db.TinTucs.Where(n => n.MaTheLoaiTinTuc == matheloaitintuc).ToList();
            if (tintuc.Count == 0)
            {
                ViewBag.ThongBao = "Không có code nào";
            }
            return View(tintuc);
        }
    }
}

ChiaSeCode_TH/Areas/Admin/Views/TinTucs/Create.cshtml
@model ChiaSeCode_TH.Models.TinTuc

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/LayoutAdmin/LayoutAdmin.cshtml";
}
@Html.Action("MenuAD", "HienThiAdmin")
<a href="#Xem" class="btn btn-danger" style="z-index: 1000; margin-top:5%; width:20%; margin-left: 2%"><b>THÊM</b></a>
<iframe src="/Admin/TinTucs/Index" style="width: 100%; height: 600px; margin-top: 1%"></iframe>
<div id="Xem" style="margin-top: 5%">
    @using (Html.BeginForm("Create", "TinTucs", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div>
                <div class="form-group" style="width:50%; float: left">
                    <b class="control-label col-md-2" style="color:saddlebrown"><i class="fa fa-newspaper">&nbsp;</i>Tên tin tức<b style="color: red;">*</b></b>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TenTinTuc, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TenTinTuc, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group" style="width:50%; float: right">
                    <b class="control-label col-md-2" style="color:saddlebrown"><i class="fas fa-align-justify">&nbsp;</i>Thể loại:<b style="color: red;">*</b></b>
                    <div class="col-md-10">
                        @Html.DropDownList("MaTheLoaiTinTuc", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.MaTheLoaiTinTuc, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div>
                <div class="form-group" style="width:50%; float: left">
                    <b class="control-label col-md-2" style="color:saddlebrown"><i class="fa fa-image">&nbsp;</i>Ảnh tiêu đề<b style="color: red;">*</b></b>
                    <div class="col-md-10">
                        <input type="file" class="form-control" name="fileUpload" />
                    </div>
                </div>

                <div class="form-group" style="width:50%; float: right">
                    <b class="control-label col-md-2" style="color:saddlebrown"><i class="fas fa-eye">&nbsp;</i>Lượt xem ảo<b style="color: red;">*</b></b>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.LuotXemTinTuc, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LuotXemTinTuc, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div>
                <div class="form-group" style="width:50%; float: left">
                    <b class="control-label col-md-2" style="color:saddlebrown"><i class="fa fa-user">&nbsp;</i>Người đăng<b style="color: red;">*</b></b>
                    <div class="col-md-10">
                        @Html.DropDownList("MaNguoiDung", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.MaNguoiDung, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group" style="width:50%; float: right">
                    <b class="control-label col-md-2" style="color:saddlebrown"><i class="fas fa-edit">&nbsp;</i>Nội dung<b style="color: red;">*</b></b>
                    <div class="col-md-10">
                        <textarea class="ckeditor" name="NoiDungTinTuc">

                        </textarea>
                    </div>
                </div>
            </div>
            <div class="form-group container">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Thêm" class="btn btn-danger" style="width: 50%; margin-left: 30%" />
                </div>
            </div>
        </div>
    }
</div>

ChiaSeCode_TH/Areas/Admin/Views/TinTucs/Delete.cshtml
@model ChiaSeCode_TH.Models.TinTuc

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/LayoutAdmin/LayoutAdmin.cshtml";
}

<br /><div style="text-align: center; font-size: 20px; color: red; font-weight: bold"><a href="/Admin/TinTucs/Index" style="font-size: 30px;"><b><i class="fas fa-chevron-circle-left">&nbsp;&nbsp;</i></b></a>Xóa: @Model.TenTinTuc [Mã: @Model.MaTinTuc]&nbsp;&nbsp;&nbsp;<a href="/Admin/TinTucs/Edit/@Model.MaTinTuc" style="font-size: 30px"><b><i class="fa fa-edit"></i></b></a></div>
<br />
<div>
    <div class="dl-horizontal">
        <div class="container">
            <img src="@Url.Content("~/HinhAnh/"+Model.AnhTinTuc)" style="border-radius: 10px; float: left; width: 20%; height: 150px" />
            <span>&nbsp;<b><i class="fa fa-newspaper">&nbsp;</i>Tên tin tức:</b><b style="color: forestgreen;">&nbsp;@Html.DisplayFor(model => model.TenTinTuc)</b></span>
            <br />
            <span>&nbsp;<b><i class="fa fa-calendar-week">&nbsp;</i>Ngày đăng:</b><b style="color: forestgreen;">&nbsp;  @Html.DisplayFor(model => model.NgayDangTinTuc)</b></span>
            <br />
            <span>&nbsp;<b><i class="fa fa-eye">&nbsp;</i>Lượt xem:</b><b style="color: forestgreen;">&nbsp; @Html.DisplayFor(model => model.LuotXemTinTuc)</b></span>
            <br />
            <span>&nbsp;<b><i class="fas fa-align-justify">&nbsp;</i>Thể loại:</b><b style="color: forestgreen;">&nbsp; @Html.DisplayFor(model => model.TheLoaiTinTuc.TenTheLoaiTinTuc)</b></span>
            <br />
            <span>&nbsp;<b><i class="fas fa-mail-bulk">&nbsp;</i>Email:</b><b style="color: forestgreen;">&nbsp; @Html.DisplayFor(model => model.NguoiDung.Email)</b></span>
        </div>

    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-danger" style="width: 20%; margin-left: 38%; margin-top: 5%" />
        </div>
    }
</div>

ChiaSeCode_TH/Areas/Admin/Views/TinTucs/Details.cshtml
@model ChiaSeCode_TH.Models.TinTuc

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/LayoutAdmin/LayoutAdmin.cshtml";
}

<div>
    <br /><div style="text-align: center; font-size: 20px; color: red; font-weight: bold"><a href="/Admin/TinTucs/Index" style="font-size: 30px;"><b><i class="fas fa-chevron-circle-left">&nbsp;&nbsp;</i></b></a>Xem: @Model.TenTinTuc [Mã: @Model.MaTinTuc]&nbsp;&nbsp;&nbsp;<a href="/Admin/TinTucs/Edit/@Model.MaTinTuc" style="font-size: 30px"><b><i class="fa fa-edit"></i></b></a></div>
    <br />
    <div class="dl-horizontal">
        <div class="container">
            <img src="@Url.Content("~/HinhAnh/"+Model.AnhTinTuc)" style="border-radius: 10px; float: left; width: 20%; height: 150px" />
            <span>&nbsp;<b><i class="fa fa-newspaper">&nbsp;</i>Tên tin tức:</b><b style="color: forestgreen;">&nbsp;@Html.DisplayFor(model => model.TenTinTuc)</b></span>
            <br />
            <span>&nbsp;<b><i class="fa fa-calendar-week">&nbsp;</i>Ngày đăng:</b><b style="color: forestgreen;">&nbsp;  @Html.DisplayFor(model => model.NgayDangTinTuc)</b></span>
            <br />
            <span>&nbsp;<b><i class="fa fa-eye">&nbsp;</i>Lượt xem:</b><b style="color: forestgreen;">&nbsp; @Html.DisplayFor(model => model.LuotXemTinTuc)</b></span>
            <br />
            <span>&nbsp;<b><i class="fas fa-align-justify">&nbsp;</i>Thể loại:</b><b style="color: forestgreen;">&nbsp; @Html.DisplayFor(model => model.TheLoaiTinTuc.TenTheLoaiTinTuc)</b></span>
            <br />
            <span>&nbsp;<b><i class="fas fa-mail-bulk">&nbsp;</i>Email:</b><b style="color: forestgreen;">&nbsp; @Html.DisplayFor(model => model.NguoiDung.Email)</b></span>
        </div>
        <br />
        <div class="container">
            <div style="width: 100%; float: left;">
                <div style="background-color: forestgreen; width: 35%; height: 35px; border-radius: 10px 10px 0px 0px;">
                    <span style="color: white; margin-left: 18%; font-size: 20px;">Nội dung cài đặt</span>
                </div>
                <div style="border: 1px solid forestgreen; width: 100%; height: 100%; border-radius: 0px 0px 0px 10px;">
                    <span class="container">@Html.Raw(Model.NoiDungTinTuc)</span>
                </div>
            </div>
        </div>
    </div>
</div>

ChiaSeCode_TH/Areas/Admin/Views/TinTucs/Edit.cshtml
@model ChiaSeCode_TH.Models.TinTuc

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/LayoutAdmin/LayoutAdmin.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <br /><div style="text-align: center; font-size: 20px; color: red; font-weight: bold"><a href="/Admin/TinTucs/Index" style="font-size: 30px;"><b><i class="fas fa-chevron-circle-left">&nbsp;&nbsp;</i></b></a>Sửa: @Model.TenTinTuc [Mã: @Model.MaTinTuc]&nbsp;&nbsp;&nbsp;<a href="/Admin/TinTucs/Details/@Model.MaTinTuc" style="font-size: 30px"><b><i class="fa fa-eye"></i></b></a></div>
        <br />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaTinTuc)


        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div>
                <div class="form-group" style="width:50%; float: left">
                    <b class="control-label col-md-2" style="color:saddlebrown"><i class="fa fa-newspaper">&nbsp;</i>Tên tin tức<b style="color: red;">*</b></b>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TenTinTuc, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TenTinTuc, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group" style="width:50%; float: right">
                    <b class="control-label col-md-2" style="color:saddlebrown"><i class="fas fa-align-justify">&nbsp;</i>Thể loại:<b style="color: red;">*</b></b>
                    <div class="col-md-10">
                        @Html.DropDownList("MaTheLoaiTinTuc", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.MaTheLoaiTinTuc, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div>
                <div class="form-group" style="width:50%; float: left">
                    <b class="control-label col-md-2" style="color:saddlebrown"><i class="fa fa-image">&nbsp;</i>Ảnh tiêu đề<b style="color: red;">*</b></b>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.AnhTinTuc, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AnhTinTuc, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group" style="width:50%; float: right">
                    <b class="control-label col-md-2" style="color:saddlebrown"><i class="fas fa-eye">&nbsp;</i>Lượt xem ảo<b style="color: red;">*</b></b>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.LuotXemTinTuc, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LuotXemTinTuc, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div>
                <div class="form-group" style="width:50%; float: left">
                    <b class="control-label col-md-2" style="color:saddlebrown"><i class="fa fa-user">&nbsp;</i>Người đăng<b style="color: red;">*</b></b>
                    <div class="col-md-10">
                        @Html.DropDownList("MaNguoiDung", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.MaNguoiDung, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group" style="width:50%; float: right">
                    <b class="control-label col-md-2" style="color:saddlebrown"><i class="fas fa-calendar-week">&nbsp;</i>Ngày đăng<b style="color: red;">*</b></b>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.NgayDangTinTuc, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NgayDangTinTuc, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div>
                <div class="form-group" style="width:50%; float: left">
                    <b class="control-label col-md-2" style="color:saddlebrown"><i class="fa fa-user">&nbsp;</i>Người đăng<b style="color: red;">*</b></b>
                    <div class="col-md-10">
                        @Html.DropDownList("MaNguoiDung", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.MaNguoiDung, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group" style="width:50%; float: right">
                    <b class="control-label col-md-2" style="color:saddlebrown"><i class="fas fa-edit">&nbsp;</i>Nội dung<b style="color: red;">*</b></b>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.NoiDungTinTuc, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NoiDungTinTuc, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Lưu" class="btn btn-danger" style="width: 20%; margin-left: 30%; margin-top: 5%" />
                </div>
            </div>
        </div>
    </div>
}

ChiaSeCode_TH/Areas/Admin/Views/TinTucs/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model PagedList.PagedList<ChiaSeCode_TH.Models.TinTuc>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/LayoutAdmin/LayoutAdmin.cshtml";
}

<table class="table table-striped">
    <tr>
        <th>
            <b><i class="fa fa-newspaper">&nbsp;</i>Tên tin tức</b>
        </th>
        <th>
            <b><i class="fas fa-calendar-week">&nbsp;</i>Ngày đăng</b>
        </th>
        <th>
            <b><i class="fa fa-image">&nbsp;</i>Ảnh</b>
        </th>
        <th>
            <b><i class="fa fa-eye">&nbsp;</i>Lượt xem</b>
        </th>
        <th>
            <b><i class="fas fa-mail-bulk">&nbsp;</i>Email</b>
        </th>
        <th>
            <b><i class="fa fa-align-justify">&nbsp;</i>Thể loại</b>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TenTinTuc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayDangTinTuc)
            </td>
            <td>
                <img src="@Url.Content("~/HinhAnh/"+item.AnhTinTuc)" style="width:100px; height:50px;" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LuotXemTinTuc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NguoiDung.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TheLoaiTinTuc.TenTheLoaiTinTuc)
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.MaTinTuc }) |
                @Html.ActionLink("Xem", "Details", new { id = item.MaTinTuc }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.MaTinTuc })
            </td>
        </tr>
    }
</table>
<center>@Html.PagedListPager(Model, Page => Url.Action("Index", new { Page = Page }))</center>